from sqlalchemy import Column, Integer, String, DateTime, Text, Boolean, Float, join, ForeignKey
from sqlalchemy.dialects.mysql import JSON
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import column_property
Base = declarative_base()


class TruckDataPoint(Base):
    __tablename__ = 'truck_data_point'

    TripID = Column(Integer, primary_key=True)
    DriverID = Column(String(512))
    VehicleID = Column(String(512))
    VehicleSegmentID = Column(String(512))
    AvgFuelConsumption_per100km = Column(Float)
    TotalFuel = Column(Float)
    TotalDistance = Column(Float)
    TimeTorqueHigh70_normalized = Column(Float)
    TimeTorqueHigh50_normalized = Column(Float)
    TimeTorqueHigh30_normalized = Column(Float)
    TimeTorqueAboveThreshold_normalized = Column(Float)
    TimeIdling_normalized = Column(Float)
    TimeGreenSpot_normalized = Column(Float)
    TimeHarshAcceleration_normalized = Column(Float)
    AvgEngineTorque = Column(Float)
    AvgTachoSpeed = Column(Float)
    AvgPositionThrottle = Column(Float)
    NrUpgearChanges_per100km = Column(Float)
    MaxPositionThrottle = Column(Float)
    TimesGearsNegativeCorrect_per100KM = Column(Float)
    TimesGearsPositiveCorrect_per100km = Column(Float)
    TimeGear1_norm = Column(Float)
    TimeGear10_norm = Column(Float)
    TimeGear11_norm = Column(Float)
    TimeGear12_norm = Column(Float)
    TimeGear13_norm = Column(Float)
    TimeGear14_norm = Column(Float)
    TimeGear15_norm = Column(Float)
    TimeGear16_norm = Column(Float)
    TimeGear2_norm = Column(Float)
    TimeGear3_norm = Column(Float)
    TimeGear4_norm = Column(Float)
    TimeGear5_norm = Column(Float)
    TimeGear6_norm = Column(Float)
    TimeGear7_norm = Column(Float)
    TimeGear9_norm = Column(Float)
    TimeGear8_norm = Column(Float)
    NrStops_per100km = Column(Float)
    NrBrakes_per100km = Column(Float)
    TimeBrakes_normalized = Column(Float)
    AltitiudeUp_dm_per_km = Column(Float)
    AltitudeDown_dm_per_km = Column(Float)
    AvgFuelRate = Column(Float)
    AvgRPM = Column(Float)
    DistanceCruising_normalized = Column(Float)
    DistanceGreenSpot_normalized = Column(Float)
    DistanceNoThrottlePush_normalized = Column(Float)
    TimeAboveSpeed_normalized = Column(Float)
    TimeCruising_normalized = Column(Float)
    TimeDriving = Column(Float)
    Driver_Cluster = Column(Float)
    Trip_Cluster = Column(Float)
    NrHarshAcceleration_per100km = Column(Float)
